name: postgres
services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 12345678admin
        ports:
            - '1000:5432'
        volumes:
            - ./postgres:/var/lib/postgresql

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: 12345678admin
        volumes:
            - ./pgadmin:/var/lib/pgadmin
        ports:
            - '80:80'
        depends_on:
            - postgres
