
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const WorkEventTypes = {
  WORK: 'WORK',
  BREAK: 'BREAK'
} as const

export type WorkEventTypes = (typeof WorkEventTypes)[keyof typeof WorkEventTypes]
