
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkEvent
 * 
 */
export type WorkEventModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkEventPayload>

export type AggregateWorkEvent = {
  _count: WorkEventCountAggregateOutputType | null
  _min: WorkEventMinAggregateOutputType | null
  _max: WorkEventMaxAggregateOutputType | null
}

export type WorkEventMinAggregateOutputType = {
  id: string | null
  workerId: string | null
  type: $Enums.WorkEventTypes | null
  timeStart: Date | null
  timeEnd: Date | null
}

export type WorkEventMaxAggregateOutputType = {
  id: string | null
  workerId: string | null
  type: $Enums.WorkEventTypes | null
  timeStart: Date | null
  timeEnd: Date | null
}

export type WorkEventCountAggregateOutputType = {
  id: number
  workerId: number
  type: number
  timeStart: number
  timeEnd: number
  _all: number
}


export type WorkEventMinAggregateInputType = {
  id?: true
  workerId?: true
  type?: true
  timeStart?: true
  timeEnd?: true
}

export type WorkEventMaxAggregateInputType = {
  id?: true
  workerId?: true
  type?: true
  timeStart?: true
  timeEnd?: true
}

export type WorkEventCountAggregateInputType = {
  id?: true
  workerId?: true
  type?: true
  timeStart?: true
  timeEnd?: true
  _all?: true
}

export type WorkEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkEvent to aggregate.
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkEvents to fetch.
   */
  orderBy?: Prisma.WorkEventOrderByWithRelationInput | Prisma.WorkEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkEvents
  **/
  _count?: true | WorkEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkEventMaxAggregateInputType
}

export type GetWorkEventAggregateType<T extends WorkEventAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkEvent[P]>
}




export type WorkEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkEventWhereInput
  orderBy?: Prisma.WorkEventOrderByWithAggregationInput | Prisma.WorkEventOrderByWithAggregationInput[]
  by: Prisma.WorkEventScalarFieldEnum[] | Prisma.WorkEventScalarFieldEnum
  having?: Prisma.WorkEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkEventCountAggregateInputType | true
  _min?: WorkEventMinAggregateInputType
  _max?: WorkEventMaxAggregateInputType
}

export type WorkEventGroupByOutputType = {
  id: string
  workerId: string
  type: $Enums.WorkEventTypes
  timeStart: Date
  timeEnd: Date
  _count: WorkEventCountAggregateOutputType | null
  _min: WorkEventMinAggregateOutputType | null
  _max: WorkEventMaxAggregateOutputType | null
}

type GetWorkEventGroupByPayload<T extends WorkEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkEventGroupByOutputType[P]>
      }
    >
  >



export type WorkEventWhereInput = {
  AND?: Prisma.WorkEventWhereInput | Prisma.WorkEventWhereInput[]
  OR?: Prisma.WorkEventWhereInput[]
  NOT?: Prisma.WorkEventWhereInput | Prisma.WorkEventWhereInput[]
  id?: Prisma.StringFilter<"WorkEvent"> | string
  workerId?: Prisma.StringFilter<"WorkEvent"> | string
  type?: Prisma.EnumWorkEventTypesFilter<"WorkEvent"> | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
  timeEnd?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
  worker?: Prisma.XOR<Prisma.WorkerScalarRelationFilter, Prisma.WorkerWhereInput>
}

export type WorkEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timeStart?: Prisma.SortOrder
  timeEnd?: Prisma.SortOrder
  worker?: Prisma.WorkerOrderByWithRelationInput
}

export type WorkEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkEventWhereInput | Prisma.WorkEventWhereInput[]
  OR?: Prisma.WorkEventWhereInput[]
  NOT?: Prisma.WorkEventWhereInput | Prisma.WorkEventWhereInput[]
  workerId?: Prisma.StringFilter<"WorkEvent"> | string
  type?: Prisma.EnumWorkEventTypesFilter<"WorkEvent"> | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
  timeEnd?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
  worker?: Prisma.XOR<Prisma.WorkerScalarRelationFilter, Prisma.WorkerWhereInput>
}, "id">

export type WorkEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timeStart?: Prisma.SortOrder
  timeEnd?: Prisma.SortOrder
  _count?: Prisma.WorkEventCountOrderByAggregateInput
  _max?: Prisma.WorkEventMaxOrderByAggregateInput
  _min?: Prisma.WorkEventMinOrderByAggregateInput
}

export type WorkEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkEventScalarWhereWithAggregatesInput | Prisma.WorkEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkEventScalarWhereWithAggregatesInput | Prisma.WorkEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkEvent"> | string
  workerId?: Prisma.StringWithAggregatesFilter<"WorkEvent"> | string
  type?: Prisma.EnumWorkEventTypesWithAggregatesFilter<"WorkEvent"> | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeWithAggregatesFilter<"WorkEvent"> | Date | string
  timeEnd?: Prisma.DateTimeWithAggregatesFilter<"WorkEvent"> | Date | string
}

export type WorkEventCreateInput = {
  id?: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
  worker: Prisma.WorkerCreateNestedOneWithoutWorkEventsInput
}

export type WorkEventUncheckedCreateInput = {
  id?: string
  workerId: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
}

export type WorkEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  worker?: Prisma.WorkerUpdateOneRequiredWithoutWorkEventsNestedInput
}

export type WorkEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workerId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkEventCreateManyInput = {
  id?: string
  workerId: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
}

export type WorkEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workerId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkEventListRelationFilter = {
  every?: Prisma.WorkEventWhereInput
  some?: Prisma.WorkEventWhereInput
  none?: Prisma.WorkEventWhereInput
}

export type WorkEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timeStart?: Prisma.SortOrder
  timeEnd?: Prisma.SortOrder
}

export type WorkEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timeStart?: Prisma.SortOrder
  timeEnd?: Prisma.SortOrder
}

export type WorkEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workerId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  timeStart?: Prisma.SortOrder
  timeEnd?: Prisma.SortOrder
}

export type WorkEventCreateNestedManyWithoutWorkerInput = {
  create?: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput> | Prisma.WorkEventCreateWithoutWorkerInput[] | Prisma.WorkEventUncheckedCreateWithoutWorkerInput[]
  connectOrCreate?: Prisma.WorkEventCreateOrConnectWithoutWorkerInput | Prisma.WorkEventCreateOrConnectWithoutWorkerInput[]
  createMany?: Prisma.WorkEventCreateManyWorkerInputEnvelope
  connect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
}

export type WorkEventUncheckedCreateNestedManyWithoutWorkerInput = {
  create?: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput> | Prisma.WorkEventCreateWithoutWorkerInput[] | Prisma.WorkEventUncheckedCreateWithoutWorkerInput[]
  connectOrCreate?: Prisma.WorkEventCreateOrConnectWithoutWorkerInput | Prisma.WorkEventCreateOrConnectWithoutWorkerInput[]
  createMany?: Prisma.WorkEventCreateManyWorkerInputEnvelope
  connect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
}

export type WorkEventUpdateManyWithoutWorkerNestedInput = {
  create?: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput> | Prisma.WorkEventCreateWithoutWorkerInput[] | Prisma.WorkEventUncheckedCreateWithoutWorkerInput[]
  connectOrCreate?: Prisma.WorkEventCreateOrConnectWithoutWorkerInput | Prisma.WorkEventCreateOrConnectWithoutWorkerInput[]
  upsert?: Prisma.WorkEventUpsertWithWhereUniqueWithoutWorkerInput | Prisma.WorkEventUpsertWithWhereUniqueWithoutWorkerInput[]
  createMany?: Prisma.WorkEventCreateManyWorkerInputEnvelope
  set?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  disconnect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  delete?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  connect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  update?: Prisma.WorkEventUpdateWithWhereUniqueWithoutWorkerInput | Prisma.WorkEventUpdateWithWhereUniqueWithoutWorkerInput[]
  updateMany?: Prisma.WorkEventUpdateManyWithWhereWithoutWorkerInput | Prisma.WorkEventUpdateManyWithWhereWithoutWorkerInput[]
  deleteMany?: Prisma.WorkEventScalarWhereInput | Prisma.WorkEventScalarWhereInput[]
}

export type WorkEventUncheckedUpdateManyWithoutWorkerNestedInput = {
  create?: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput> | Prisma.WorkEventCreateWithoutWorkerInput[] | Prisma.WorkEventUncheckedCreateWithoutWorkerInput[]
  connectOrCreate?: Prisma.WorkEventCreateOrConnectWithoutWorkerInput | Prisma.WorkEventCreateOrConnectWithoutWorkerInput[]
  upsert?: Prisma.WorkEventUpsertWithWhereUniqueWithoutWorkerInput | Prisma.WorkEventUpsertWithWhereUniqueWithoutWorkerInput[]
  createMany?: Prisma.WorkEventCreateManyWorkerInputEnvelope
  set?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  disconnect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  delete?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  connect?: Prisma.WorkEventWhereUniqueInput | Prisma.WorkEventWhereUniqueInput[]
  update?: Prisma.WorkEventUpdateWithWhereUniqueWithoutWorkerInput | Prisma.WorkEventUpdateWithWhereUniqueWithoutWorkerInput[]
  updateMany?: Prisma.WorkEventUpdateManyWithWhereWithoutWorkerInput | Prisma.WorkEventUpdateManyWithWhereWithoutWorkerInput[]
  deleteMany?: Prisma.WorkEventScalarWhereInput | Prisma.WorkEventScalarWhereInput[]
}

export type EnumWorkEventTypesFieldUpdateOperationsInput = {
  set?: $Enums.WorkEventTypes
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type WorkEventCreateWithoutWorkerInput = {
  id?: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
}

export type WorkEventUncheckedCreateWithoutWorkerInput = {
  id?: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
}

export type WorkEventCreateOrConnectWithoutWorkerInput = {
  where: Prisma.WorkEventWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput>
}

export type WorkEventCreateManyWorkerInputEnvelope = {
  data: Prisma.WorkEventCreateManyWorkerInput | Prisma.WorkEventCreateManyWorkerInput[]
  skipDuplicates?: boolean
}

export type WorkEventUpsertWithWhereUniqueWithoutWorkerInput = {
  where: Prisma.WorkEventWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkEventUpdateWithoutWorkerInput, Prisma.WorkEventUncheckedUpdateWithoutWorkerInput>
  create: Prisma.XOR<Prisma.WorkEventCreateWithoutWorkerInput, Prisma.WorkEventUncheckedCreateWithoutWorkerInput>
}

export type WorkEventUpdateWithWhereUniqueWithoutWorkerInput = {
  where: Prisma.WorkEventWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkEventUpdateWithoutWorkerInput, Prisma.WorkEventUncheckedUpdateWithoutWorkerInput>
}

export type WorkEventUpdateManyWithWhereWithoutWorkerInput = {
  where: Prisma.WorkEventScalarWhereInput
  data: Prisma.XOR<Prisma.WorkEventUpdateManyMutationInput, Prisma.WorkEventUncheckedUpdateManyWithoutWorkerInput>
}

export type WorkEventScalarWhereInput = {
  AND?: Prisma.WorkEventScalarWhereInput | Prisma.WorkEventScalarWhereInput[]
  OR?: Prisma.WorkEventScalarWhereInput[]
  NOT?: Prisma.WorkEventScalarWhereInput | Prisma.WorkEventScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkEvent"> | string
  workerId?: Prisma.StringFilter<"WorkEvent"> | string
  type?: Prisma.EnumWorkEventTypesFilter<"WorkEvent"> | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
  timeEnd?: Prisma.DateTimeFilter<"WorkEvent"> | Date | string
}

export type WorkEventCreateManyWorkerInput = {
  id?: string
  type: $Enums.WorkEventTypes
  timeStart: Date | string
  timeEnd: Date | string
}

export type WorkEventUpdateWithoutWorkerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkEventUncheckedUpdateWithoutWorkerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkEventUncheckedUpdateManyWithoutWorkerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumWorkEventTypesFieldUpdateOperationsInput | $Enums.WorkEventTypes
  timeStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type WorkEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workerId?: boolean
  type?: boolean
  timeStart?: boolean
  timeEnd?: boolean
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workEvent"]>

export type WorkEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workerId?: boolean
  type?: boolean
  timeStart?: boolean
  timeEnd?: boolean
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workEvent"]>

export type WorkEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workerId?: boolean
  type?: boolean
  timeStart?: boolean
  timeEnd?: boolean
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workEvent"]>

export type WorkEventSelectScalar = {
  id?: boolean
  workerId?: boolean
  type?: boolean
  timeStart?: boolean
  timeEnd?: boolean
}

export type WorkEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workerId" | "type" | "timeStart" | "timeEnd", ExtArgs["result"]["workEvent"]>
export type WorkEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}
export type WorkEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}
export type WorkEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  worker?: boolean | Prisma.WorkerDefaultArgs<ExtArgs>
}

export type $WorkEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkEvent"
  objects: {
    worker: Prisma.$WorkerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workerId: string
    type: $Enums.WorkEventTypes
    timeStart: Date
    timeEnd: Date
  }, ExtArgs["result"]["workEvent"]>
  composites: {}
}

export type WorkEventGetPayload<S extends boolean | null | undefined | WorkEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkEventPayload, S>

export type WorkEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkEventCountAggregateInputType | true
  }

export interface WorkEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkEvent'], meta: { name: 'WorkEvent' } }
  /**
   * Find zero or one WorkEvent that matches the filter.
   * @param {WorkEventFindUniqueArgs} args - Arguments to find a WorkEvent
   * @example
   * // Get one WorkEvent
   * const workEvent = await prisma.workEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkEventFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkEventFindUniqueOrThrowArgs} args - Arguments to find a WorkEvent
   * @example
   * // Get one WorkEvent
   * const workEvent = await prisma.workEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventFindFirstArgs} args - Arguments to find a WorkEvent
   * @example
   * // Get one WorkEvent
   * const workEvent = await prisma.workEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkEventFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventFindFirstOrThrowArgs} args - Arguments to find a WorkEvent
   * @example
   * // Get one WorkEvent
   * const workEvent = await prisma.workEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkEvents
   * const workEvents = await prisma.workEvent.findMany()
   * 
   * // Get first 10 WorkEvents
   * const workEvents = await prisma.workEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workEventWithIdOnly = await prisma.workEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkEventFindManyArgs>(args?: Prisma.SelectSubset<T, WorkEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkEvent.
   * @param {WorkEventCreateArgs} args - Arguments to create a WorkEvent.
   * @example
   * // Create one WorkEvent
   * const WorkEvent = await prisma.workEvent.create({
   *   data: {
   *     // ... data to create a WorkEvent
   *   }
   * })
   * 
   */
  create<T extends WorkEventCreateArgs>(args: Prisma.SelectSubset<T, WorkEventCreateArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkEvents.
   * @param {WorkEventCreateManyArgs} args - Arguments to create many WorkEvents.
   * @example
   * // Create many WorkEvents
   * const workEvent = await prisma.workEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkEventCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkEvents and returns the data saved in the database.
   * @param {WorkEventCreateManyAndReturnArgs} args - Arguments to create many WorkEvents.
   * @example
   * // Create many WorkEvents
   * const workEvent = await prisma.workEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkEvents and only return the `id`
   * const workEventWithIdOnly = await prisma.workEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkEvent.
   * @param {WorkEventDeleteArgs} args - Arguments to delete one WorkEvent.
   * @example
   * // Delete one WorkEvent
   * const WorkEvent = await prisma.workEvent.delete({
   *   where: {
   *     // ... filter to delete one WorkEvent
   *   }
   * })
   * 
   */
  delete<T extends WorkEventDeleteArgs>(args: Prisma.SelectSubset<T, WorkEventDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkEvent.
   * @param {WorkEventUpdateArgs} args - Arguments to update one WorkEvent.
   * @example
   * // Update one WorkEvent
   * const workEvent = await prisma.workEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkEventUpdateArgs>(args: Prisma.SelectSubset<T, WorkEventUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkEvents.
   * @param {WorkEventDeleteManyArgs} args - Arguments to filter WorkEvents to delete.
   * @example
   * // Delete a few WorkEvents
   * const { count } = await prisma.workEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkEvents
   * const workEvent = await prisma.workEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkEventUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkEvents and returns the data updated in the database.
   * @param {WorkEventUpdateManyAndReturnArgs} args - Arguments to update many WorkEvents.
   * @example
   * // Update many WorkEvents
   * const workEvent = await prisma.workEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkEvents and only return the `id`
   * const workEventWithIdOnly = await prisma.workEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkEvent.
   * @param {WorkEventUpsertArgs} args - Arguments to update or create a WorkEvent.
   * @example
   * // Update or create a WorkEvent
   * const workEvent = await prisma.workEvent.upsert({
   *   create: {
   *     // ... data to create a WorkEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkEvent we want to update
   *   }
   * })
   */
  upsert<T extends WorkEventUpsertArgs>(args: Prisma.SelectSubset<T, WorkEventUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkEventClient<runtime.Types.Result.GetResult<Prisma.$WorkEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventCountArgs} args - Arguments to filter WorkEvents to count.
   * @example
   * // Count the number of WorkEvents
   * const count = await prisma.workEvent.count({
   *   where: {
   *     // ... the filter for the WorkEvents we want to count
   *   }
   * })
  **/
  count<T extends WorkEventCountArgs>(
    args?: Prisma.Subset<T, WorkEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkEventAggregateArgs>(args: Prisma.Subset<T, WorkEventAggregateArgs>): Prisma.PrismaPromise<GetWorkEventAggregateType<T>>

  /**
   * Group by WorkEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkEventGroupByArgs['orderBy'] }
      : { orderBy?: WorkEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkEvent model
 */
readonly fields: WorkEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  worker<T extends Prisma.WorkerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkerDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkerClient<runtime.Types.Result.GetResult<Prisma.$WorkerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkEvent model
 */
export interface WorkEventFieldRefs {
  readonly id: Prisma.FieldRef<"WorkEvent", 'String'>
  readonly workerId: Prisma.FieldRef<"WorkEvent", 'String'>
  readonly type: Prisma.FieldRef<"WorkEvent", 'WorkEventTypes'>
  readonly timeStart: Prisma.FieldRef<"WorkEvent", 'DateTime'>
  readonly timeEnd: Prisma.FieldRef<"WorkEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkEvent findUnique
 */
export type WorkEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter, which WorkEvent to fetch.
   */
  where: Prisma.WorkEventWhereUniqueInput
}

/**
 * WorkEvent findUniqueOrThrow
 */
export type WorkEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter, which WorkEvent to fetch.
   */
  where: Prisma.WorkEventWhereUniqueInput
}

/**
 * WorkEvent findFirst
 */
export type WorkEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter, which WorkEvent to fetch.
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkEvents to fetch.
   */
  orderBy?: Prisma.WorkEventOrderByWithRelationInput | Prisma.WorkEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkEvents.
   */
  cursor?: Prisma.WorkEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkEvents.
   */
  distinct?: Prisma.WorkEventScalarFieldEnum | Prisma.WorkEventScalarFieldEnum[]
}

/**
 * WorkEvent findFirstOrThrow
 */
export type WorkEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter, which WorkEvent to fetch.
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkEvents to fetch.
   */
  orderBy?: Prisma.WorkEventOrderByWithRelationInput | Prisma.WorkEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkEvents.
   */
  cursor?: Prisma.WorkEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkEvents.
   */
  distinct?: Prisma.WorkEventScalarFieldEnum | Prisma.WorkEventScalarFieldEnum[]
}

/**
 * WorkEvent findMany
 */
export type WorkEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter, which WorkEvents to fetch.
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkEvents to fetch.
   */
  orderBy?: Prisma.WorkEventOrderByWithRelationInput | Prisma.WorkEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkEvents.
   */
  cursor?: Prisma.WorkEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkEvents.
   */
  skip?: number
  distinct?: Prisma.WorkEventScalarFieldEnum | Prisma.WorkEventScalarFieldEnum[]
}

/**
 * WorkEvent create
 */
export type WorkEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkEvent.
   */
  data: Prisma.XOR<Prisma.WorkEventCreateInput, Prisma.WorkEventUncheckedCreateInput>
}

/**
 * WorkEvent createMany
 */
export type WorkEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkEvents.
   */
  data: Prisma.WorkEventCreateManyInput | Prisma.WorkEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkEvent createManyAndReturn
 */
export type WorkEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * The data used to create many WorkEvents.
   */
  data: Prisma.WorkEventCreateManyInput | Prisma.WorkEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkEvent update
 */
export type WorkEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkEvent.
   */
  data: Prisma.XOR<Prisma.WorkEventUpdateInput, Prisma.WorkEventUncheckedUpdateInput>
  /**
   * Choose, which WorkEvent to update.
   */
  where: Prisma.WorkEventWhereUniqueInput
}

/**
 * WorkEvent updateMany
 */
export type WorkEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkEvents.
   */
  data: Prisma.XOR<Prisma.WorkEventUpdateManyMutationInput, Prisma.WorkEventUncheckedUpdateManyInput>
  /**
   * Filter which WorkEvents to update
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * Limit how many WorkEvents to update.
   */
  limit?: number
}

/**
 * WorkEvent updateManyAndReturn
 */
export type WorkEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * The data used to update WorkEvents.
   */
  data: Prisma.XOR<Prisma.WorkEventUpdateManyMutationInput, Prisma.WorkEventUncheckedUpdateManyInput>
  /**
   * Filter which WorkEvents to update
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * Limit how many WorkEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkEvent upsert
 */
export type WorkEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkEvent to update in case it exists.
   */
  where: Prisma.WorkEventWhereUniqueInput
  /**
   * In case the WorkEvent found by the `where` argument doesn't exist, create a new WorkEvent with this data.
   */
  create: Prisma.XOR<Prisma.WorkEventCreateInput, Prisma.WorkEventUncheckedCreateInput>
  /**
   * In case the WorkEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkEventUpdateInput, Prisma.WorkEventUncheckedUpdateInput>
}

/**
 * WorkEvent delete
 */
export type WorkEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
  /**
   * Filter which WorkEvent to delete.
   */
  where: Prisma.WorkEventWhereUniqueInput
}

/**
 * WorkEvent deleteMany
 */
export type WorkEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkEvents to delete
   */
  where?: Prisma.WorkEventWhereInput
  /**
   * Limit how many WorkEvents to delete.
   */
  limit?: number
}

/**
 * WorkEvent without action
 */
export type WorkEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkEvent
   */
  select?: Prisma.WorkEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkEvent
   */
  omit?: Prisma.WorkEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkEventInclude<ExtArgs> | null
}
