export interface Config {
    UBIQUITI_ACCESS_UPDATE_INTERVAL: number;
    UBIQUITI_ACCESS_ON_FAIL_UPDATE_INTERVAL: number;
    UBIQUITI_ACCESS_FULL_UPDATE_INTERVAL: number;
    UBIQUITI_ACCESS_FULL_AUTO_UPDATE_ENABLED: boolean;
    UBIQUITI_ACCESS_API_URL: string;
    UBIQUITI_ACCESS_API_KEY: string;
    UBIQUITY_ACCESS_END_WORK_DAY: string;
    SERVER_PORT: number;
}

export type ConfigKey = keyof Config;
